server:
  port: 8084
  servlet:
    context-path: /post
  address: 0.0.0.0

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin
    redis:
      host: localhost
      port: 6379
      # Sử dụng database khác với Identity Service
      database: 1
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
      cache:
        type: redis
app:
  service:
    profile:
      url: "http://localhost:8081/profile"
    notification:
      url: "http://localhost:8082/notification"
    identity:
      url: "http://localhost:8080/identity"
