server:
  port: 8086
  address: 0.0.0.0
  servlet:
    context-path: /stories

spring:
  application:
    name: story-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/story-service?authSource=admin}

    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

app:
  service:
    identity:
      url: ${IDENTITY_SERVICE_URL:http://localhost:8080/identity}
    profile:
      url: ${PROFILE_SERVICE_URL:http://localhost:8081/profile}
    notification:
      url: ${NOTIFICATION_SERVICE_URL:http://localhost:8082/notification}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always